server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name secure-web-lab.local;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;

    server_name secure-web-lab.local;

    ssl_certificate     /etc/nginx/ssl/prod/server.crt;
    ssl_certificate_key /etc/nginx/ssl/prod/server.key;

    include snippets/tls-hardening.conf;
    include snippets/security-headers.conf;

    root /var/www/secure-web-lab-prod;
    index index.html;

    autoindex off;
    add_header X-Environment "prod-lab" always;

    access_log /var/log/nginx/secure-web-lab-prod.access.log;
    error_log  /var/log/nginx/secure-web-lab-prod.error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
