server {
    listen 8081 default_server;
    listen [::]:8081 default_server;

    server_name staging.secure-web-lab.local;

    return 301 https://$host:8444$request_uri;
}

server {
    listen 8444 ssl default_server;
    listen [::]:8444 ssl default_server;

    server_name staging.secure-web-lab.local;

    ssl_certificate     /etc/nginx/ssl/staging/server.crt;
    ssl_certificate_key /etc/nginx/ssl/staging/server.key;

    include snippets/tls-hardening.conf;
    include snippets/security-headers.conf;

    root /var/www/secure-web-lab-staging;
    index index.html;

    autoindex off;
    add_header X-Environment "staging" always;

    access_log /var/log/nginx/secure-web-lab-staging.access.log;
    error_log  /var/log/nginx/secure-web-lab-staging.error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
