server {
    listen 8080 default_server;
    listen [::]:8080 default_server;

    server_name dev.secure-web-lab.local;

    return 301 https://$host:8443$request_uri;
}

server {
    listen 8443 ssl default_server;
    listen [::]:8443 ssl default_server;

    server_name dev.secure-web-lab.local;

    ssl_certificate     /etc/nginx/ssl/dev/server.crt;
    ssl_certificate_key /etc/nginx/ssl/dev/server.key;

    include snippets/tls-hardening.conf;
    include snippets/security-headers.conf;

    root /var/www/secure-web-lab-dev;
    index index.html;

    autoindex on;
    add_header X-Environment "dev" always;

    access_log /var/log/nginx/secure-web-lab-dev.access.log;
    error_log  /var/log/nginx/secure-web-lab-dev.error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
