server {
    listen 80;
    listen [::]:80;

    server_name secure-web-lab.local;

    root /var/www/secure-web-lab;
    index index.html;

    access_log /var/log/nginx/secure-web-lab.access.log;
    error_log  /var/log/nginx/secure-web-lab.error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
